[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
algorithms = { git = "https://github.com/a-isaiahharvey/algorithms-rs", branch = "main" }
anyhow = "1.0.75"
arrayvec = "0.7.4"
itertools = "0.12.0"
lazy_static = "1.4.0"
num = "0.4.1"
permutohedron = "0.2.4"
primal = "0.3.2"
rayon = "1.8"
regex = "1.10.2"
sscanf = "0.4.1"
serde_json = "1.0.108"
log = "0.4.21"
