name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Nightly build
      run: |
        rustup override set nightly
        cargo build --verbose
    - name: Run nightly tests
      run: |
        rustup override set nightly
        cargo test --verbose
